### ISSUE TITLE
First login: What's new: wording suggestions

### ISSUE THREAD

**Issue by jbicha** [CanonicalLtd/desktop-design#101]
1. I suggest using _Dock_ instead of _Launcher_ because in the Settings app, it is referred to as _Dock_.

2. I think one of the unusual parts of GNOME Shell's design is that notifications are kept in the clock menu. Therefore, I suggest naming that item _Clock, calendar, and notifications_

Since this image currently embeds the labels and are not translated, I guess we could still make adjustments now for Ubuntu 18.04 initial release.

Below is the graphic used in the proposed gnome-initial-setup 3.28.0-2ubuntu4 version.

![ubuntu-changes](https://user-images.githubusercontent.com/876259/38961302-fde6f766-4335-11e8-834e-d6a4f2109c9d.png)

**Comment by jbicha** [comment]
@Astrowatt You can run the settings app in English with this command:

`LANGUAGE=en gnome-control-center`

_Launcher_ was the word used for the similar feature in Unity but in 17.10 and 18.04 it is named _Dock_ in part because it uses a simplified version of the _Dash to Dock_ extension for GNOME Shell.

**Comment by matthewpaulthomas** [comment]
1\. Last September, Seb asked me how we should refer to the launcher in the settings UI. My answer was “Launcher”. @didrocks said that might be a problem, because that term had a “Unity connotation”, and the new launcher was based on the Dash-to-Dock extension. I replied:

> I think that a vague connotation amongst a few Gnome Shell contributors
is not nearly as important as familiarity for millions of Ubuntu users.
>
> If it did very different things from the Launcher we’ve been shipping up
till now, a different name might make more sense — but “Dock” would
still be a bad name to choose, since that’s what macOS uses.

I’m surprised to discover that it’s now called “Dock” after all. (Though it’s misspelled “dock” in one place.) But since it is, of course the first-login UI should be consistent. [Spec updated](https://docs.google.com/document/d/1IDQwpqTsB7Cmw413ApXioHeO2E9nv8bHugjxCOg9A-Q/edit#heading=h.c982dk7mudyb).

2\. The only message I‘ve ever seen in the calendar panel is “Software Updates Installed — Important OS updates have been installed”. There is absolutely nothing I can do with that information. However, I’ll take your word for it that there are sometimes useful notifications in this panel. Changed to “Calendar and notifications”.

**Comment by matthewpaulthomas** [comment]
@spencerbygraves If the text is still embedded in the graphic, this now needs an updated graphic please.

![first-login-help](https://user-images.githubusercontent.com/19801137/39478723-18997bf4-4d5b-11e8-957a-10938507c19e.png)

**Comment by spencerbygraves** [comment]
@jbicha @matthewpaulthomas Here's an SVG with the updated text. Thanks.

[New features.svg.zip](https://github.com/CanonicalLtd/desktop-design/files/1966685/New.features.svg.zip)

![image](https://user-images.githubusercontent.com/9105999/39516110-d7a21aea-4df3-11e8-8f19-20c4f9647679.png)

**Comment by jbicha** [comment]
@spencerbygraves @matthewpaulthomas 
Please keep _Window switcher_ and _Application menu_ as they were in the first image in this thread.

**Comment by spencerbygraves** [comment]
@jbicha Updated.

[New features.svg.zip](https://github.com/CanonicalLtd/desktop-design/files/1967471/New.features.svg.zip)

**Comment by jbicha** [comment]
@spencerbygraves Could you also include the .png version? The current implementation doesn't use the .svg version. Thanks!

**Comment by spencerbygraves** [comment]
@jbicha No problem, here you go. Thanks

![new features no text](https://user-images.githubusercontent.com/9105999/39532244-61f042a0-4e24-11e8-881d-c3d15d4a68d1.png)
![new features](https://user-images.githubusercontent.com/9105999/39532246-62064c6c-4e24-11e8-8ef6-9a2349464e05.png)

**Comment by jbicha** [comment]
The second image (the one with the labels) is much larger (1408 x 642 px) than the current image in bionic (704 x 342 px). Could you keep the same dimensions as the current image?

**Comment by spencerbygraves** [comment]
@jbicha Sorry, I saved it x2. Here you go...

![new features](https://user-images.githubusercontent.com/9105999/39536969-0f372f40-4e30-11e8-8975-48e6bb50b262.png)

**Comment by matthewpaulthomas** [comment]
@jbicha This looks all done now. Please reopen if there’s anything we’ve missed.
