### ISSUE TITLE
first login: Should clicking "Open Software" close the Welcome wizard?

### ISSUE THREAD

**Issue by jbicha** [CanonicalLtd/desktop-design#105]
gnome-initial-setup 3.28.0-2ubuntu6
Ubuntu 18.04

I suggest that clicking the _Open "Software" now_ button should also close the _Welcome to Ubuntu_ wizard since there is nothing else to be done.

![ubuntu-welcome-20180419-final-page](https://user-images.githubusercontent.com/876259/38996627-9a2a601c-43b9-11e8-95e2-93fcea5a93f5.png)

**Comment by matthewpaulthomas** [comment]
Thanks for the suggestion.

99% of the time, I strongly advocate following UI conventions of the platform. Consistency is important, especially when an app will be used repeatedly and/or quickly at the same time as other apps that do follow the convention.

Occasionally, though, a platform UI convention is _so_ bad that apps do measurably better by disregarding it. A famous example is hamburger menus on Android.

This screenshot shows another example: Putting buttons like “Done” in the title bar is an anti-pattern. Working your way through a screen from top to bottom, and then having to jump up above your starting point to finish, was a design compromise in iOS to save screen space in early iPhones. But as phone screens got larger, the benefit reduced (and the difficulty of reaching the buttons increased). On a desktop OS, where screens are much larger still, it makes no sense whatsoever. Even making the main button bright green, as Ubuntu 17.10+ does, can’t fix the perverse visual flow.

So when I wireframed this window, I put the “Go Back” and “Continue”/“Done” buttons in their traditional place at the bottom of the window. Since the implementation has diverged from the design, it’s a sad consequence that any button at the bottom of any page will look like it’s the final thing to do in the window, when it isn’t.

I don’t think the “Open ‘Software’ Now” button should close the window, because that would make it internally inconsistent with the “Set Up Livepatch…” button that _doesn’t_ close the window. For people to understand why this button closed the window, when that one didn’t, they would need to notice that the “Continue” button has changed to “Done” — which they almost certainly wouldn’t, because it’s hundreds of pixels away from where they are looking.
