### ISSUE TITLE
Authentication in gnome-software using gnome-online-accounts

### ISSUE THREAD

**Issue by azzar1** [CanonicalLtd/desktop-design#62]
In Bionic we introduced an Ubuntu Single Sing-On provider in Gnome Online Accounts:
![image](https://user-images.githubusercontent.com/3677105/37522998-f4bdc9f0-2925-11e8-94b9-9e696f40d43a.png)

The idea is to use this e.g. in Ubuntu Software to purchase snaps. Gnome-online-accounts requires the user to use gnome-control-center to add/remove accounts.  Can you please help designing the user interaction in order to login and/or choose from an account? Please consider that none/one/two-or-more ubuntu sso acocunts can be setup at any given time.

**Comment by azzar1** [comment]
Also, please note that atm there is no way to logout once logged in. So what do you think about the possibility to add a way to logout?

**Comment by matthewpaulthomas** [comment]
@azzar1 I’m (pleasantly!) surprised to see a native GUI for Ubuntu SSO sign-up, since I’d been told that its API was deprecated.

Unfortunately I don’t understand what you mean by “login and/or choose from an account”. Do you mean, the ability to grant/deny an app (like software-properties-gtk) access to your SSO account, and choose between them if you have more than one? If so, why doesn’t gnome-online-accounts already provide a single UI for that for all account types?

**Comment by azzar1** [comment]
> Do you mean, granting/denying an app (like software-properties-gtk) access to your SSO account

@matthewpaulthomas First of all a gnome-online-account client (e.g. gnome-software, software-properties) CAN access the list of accounts without asking user-permission. 

>  and choosing between SSO accounts if you have more than one? 

The login dialog is created client-side by gnome-sofware in order to let the user select an account. Just to make it clear, in theory gnome-software could pick a random ubuntu-sso account and use its credentials. software-properties-gtk requires the same type of dialog because there is the exact same problem. 

>  If so, why doesn’t gnome-online-accounts already provide a single UI for that for all account types?

I don't know why, but such type of UI it's not  provided by gnome-online-account. It would be nice to have it there, but it requires a re-design of GOA APIs. Next cycle we need to start a discussion with upstream about this issue.  For the moment we need to build the dialog client-side.

**Comment by matthewpaulthomas** [comment]
@azzar1 Thanks for those helpful answers.

I do very much think that gnome-online-accounts should provide its own authentication UI — and, when confined at least, not even _allow_ access otherwise — for the same reason as [ubuntu-online-accounts on Ubuntu Touch](https://wiki.ubuntu.com/OnlineAccounts?action=recall&rev=29#App_access), and the same reason as PolicyKit: because it’s something that we shouldn’t trust apps not to lie about.

So I think gnome-software’s auth UI, in the short term, should look as similar as practical to how Online Accounts’s auth UI should look in the long term. That way, once the UI is transferred from gnome-software to gnome-online-accounts, users won’t have to relearn anything. (I don’t think there’s any security problem here, because there’s no point in an app mimicking a system dialog if that won’t give it access to anything. A malicious app could try clickjacking, by mimicking the system dialog with the buttons reversed, closing and triggering the real dialog just before you click. But us mimicking the system dialog now doesn’t make that attack any more likely, and the Online Accounts auth UI should include [clickjacking prevention like snap interfaces will](https://wiki.ubuntu.com/SecurityPermissions?action=recall&rev=39#If_the_interface_has_an_installed_implementation) anyway.)

So, this design is fairly simple: adapting all the variations from the ubuntu-online-accounts auth UI, to follow my PC layout for snap interface auth UI. The hardest parts are the account selector for the two-or-more case, and positioning the anti-clickjack spinner vs. the “Add Another…” / “Remind Me Later” button.

**Comment by 8none1** [comment]
@mpt wrote: "@azzar1 I’m (pleasantly!) surprised to see a native GUI for Ubuntu SSO sign-up, since I’d been told that its API was deprecated."

It's the API to *create* new accounts that's been deprecated.

**Comment by matthewpaulthomas** [comment]
@azzar1 Before I get another designer to review this, can you let me know whether at least I’ve understood the sign-in use case correctly?
![ubuntu-software](https://user-images.githubusercontent.com/19801137/38507417-57a8688a-3c14-11e8-9dba-59165e19fe6b.png)

(I think the sign-out use case involves completely separate UI.)

**Comment by azzar1** [comment]
@matthewpaulthomas This looks good the only problem that I see is that we can't implement the "No Ubuntu One accounts stored" design because it's not possible to use an embedded WebView to perform the sign-in.  The others two looks fine and doable from my point of view.

**Comment by matthewpaulthomas** [comment]
> it's not possible to use an embedded WebView

So, what’s the alternative?

If it’s opening a browser window,
1. what magical properties does a browser window have that a WebView doesn’t? 🤔
1. how would we tell when you’ve finished signing in or registering?

**Comment by matthewpaulthomas** [comment]
Revised design:

No Ubuntu One accounts stored
![ubuntu-software](https://user-images.githubusercontent.com/19801137/38986966-1632a352-43c6-11e8-9f30-4fada71b78ce.png)

**Comment by azzar1** [comment]
Are we going to show this every time an Ubuntu One account is required or are we going to remember the user choice?

**Comment by matthewpaulthomas** [comment]
I think the only point in prompting again would be as a security measure, in case you’ve left your session unattended and your 7-year-old kid tries to buy Super-Expensive Video Editor Pro Edition.

In that case, though, merely saying “To buy software, you need to use your Ubuntu One account” wouldn’t protect you at all. What you should actually see at that point is the Online Accounts sign-in dialog, not any of the dialogs I’ve drawn here.

**Comment by Greggless** [comment]
### Review
@matthewpaulthomas looks clean simple, and follows conventions of other sign in/out dialogs. I assume `[Sign in / register]` opens...
> The login dialog provided by gnome-online-accounts.

but just to clarify:
> I think the only point in prompting again would be as a security measure.

How is the calculated? Time AFK? Switching applications? Logged out of session?

Would the sign out experience be part of this issue or is that another piece of work?

**Comment by matthewpaulthomas** [comment]
> I assume [Sign in / register] opens...
>> The login dialog provided by gnome-online-accounts.

@Greggless Correct.

>> I think the only point in prompting again would be as a security measure.
>
> How is th[at] calculated? Time AFK? Switching applications? Logged out of session?

Those are all good possibilities. But I think that’s outside the scope of this issue — probably something to design after software purchases have been integrated.

**Comment by matthewpaulthomas** [comment]
So, it seems that gnome-software has no menu bar, and nor does it have any other out-of-the-way UI where we could put things like account status and sign-out.

In other Gnome apps — for example, Files, Calendar, Text Editors, and To Do — there is a hamburger menu. Hamburger menus are an anti-pattern in desktop apps (for most, though not all, of the same reasons that they’re an anti-pattern in Web apps). But unlike some Gnome anti-patterns, it’s not _so_ bad that it’s worth being inconsistent with the rest of the core apps.

So, I propose that we add a menu to gnome-software, right of the search button (as in Files and Calendar), that for now contains two items: “Sign In…”, and “Sign Out {Ubuntu One ID}”.

![gnome-software-menu](https://user-images.githubusercontent.com/19801137/39369613-ac7ca7e4-4a34-11e8-9283-cfac5ffbb1d9.png)

**Comment by Greggless** [comment]
1. Is the 'burger' menu an icon that is used in Gnome/Ubuntu? Would a more conventional 'account' icon be more appropriate?
2. The [design above](https://github.com/CanonicalLtd/desktop-design/issues/62#issuecomment-382689517) implies that you can be signed in with multiple accounts (AIUI). How does the sign out work with multiple accounts?
3. If you are already signed in, is there a need to show 'sign in..'? Or is that the pattern Ubuntu follows?

**Comment by matthewpaulthomas** [comment]
@Greggless Good questions.

1. I gave examples of other Gnome/Ubuntu apps where this menu is used (“for example, Files, Calendar, Text Editor[], and To Do”) and mentioned that I was putting this menu in the same place as other apps do. I like your suggestion of using an account-ish icon instead. But I expect the menu would accumulate items in future. Some of those items might be account-related (Payment Details, Previous Purchases, My Reviews), but others might not (Copy Web Link, Terms of Use, Help).

2. “Sign In…” is disabled because you are already signed in. So, you can’t be signed in with multiple accounts.

3. I could easily have had just one menu item, rather than two, since only one of them is enabled at a time. I chose two because I thought it would be slightly clearer.

How about this: instead of

When signed out | When signed in
-|-
“Sign In…” | “Sign In…” (disabled)
“Sign Out” (disabled) | “Sign Out x@example.org”

we could have

When signed out | When signed in
-|-
“Sign In…” | “Signed in as x@example.org” (disabled)
“Sign Out” (disabled) | “Sign Out”

What do you think?

**Comment by matthewpaulthomas** [comment]
@Greggless As I said, I thought it would be slightly clearer. To be more specific, if you were looking for the “Sign In…” item and found it disabled, that would at least reassure you that you were in the right place, as opposed to just finding a “Sign Out” item. (But then, they’re often mutually exclusive on Web sites, so maybe I’m worrying over nothing.)

A second, temporary, reason is that a menu with two items looks less feeble than a menu with one item.

**Comment by matthewpaulthomas** [comment]
Following discussion this morning, I’m updating the design to follow my proposal above, where “Sign In…” changes to a disabled “Signed in as {ID}”.

![ubuntu-software-menu](https://user-images.githubusercontent.com/19801137/39470047-77459e76-4d33-11e8-8219-832ad7e83c0d.png)
